### ISSUE TITLE
Crash when a reportback-items request times out

### ISSUE THREAD

**Issue by jonuy** [DoSomething/LetsDoThis-Android#104]
We're seeing this happen a little more frequently on Thor, but could probably replicate it by simulating poor connection on the emulator or something.

```
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp: ---- ERROR https://thor.dosomething.org/api/v1/reportback-items.json?status=promoted&campaigns=2186%2C2805%2C2043&count=20&random=false&page=1
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp: java.io.InterruptedIOException: timeout
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at okio.AsyncTimeout.exit(AsyncTimeout.java:249)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:295)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.Call.getResponse(Call.java:272)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at com.squareup.okhttp.Call.execute(Call.java:79)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at retrofit.client.OkClient.execute(OkClient.java:53)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at $Proxy2.reportBackList(Unknown Source)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at org.dosomething.letsdothis.tasks.BaseReportBackListTask.run(BaseReportBackListTask.java:47)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at co.touchlab.android.threading.tasks.TaskQueue$ExeTask.run(TaskQueue.java:176)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at android.os.Handler.handleCallback(Handler.java:739)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at android.os.Looper.loop(Looper.java:135)
10-13 11:32:31.533 1957-2019/org.dosomething.letsdothis D/LDTHttp:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-13 11:32:31.534 1957-2019/org.dosomething.letsdothis D/LDTHttp: ---- END ERROR
```

**Comment by jonuy** [comment]
This hasn't been reported as a problem again for over a month, so closing out for now.
